### ISSUE TITLE
failed to install ver 1.5.0 or above via pip (install ver 1.4.0 is fine)

### ISSUE THREAD

**Issue by ygl-rg** [siddhantgoel/streaming-form-data#35]
Hi

   I have tried to install this module via pip several times without success.  I attached the ERROR log here

"ERROR: Command errored out with exit status 1:
     command: /home/pi/py375/bin/python3.7 /home/pi/py375/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpf9arkynj
         cwd: /tmp/pip-install-8qybjrwk/streaming-form-data
    Complete output (14 lines):
    Traceback (most recent call last):
      File "/home/pi/py375/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 257, in <module>
        main()
      File "/home/pi/py375/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 240, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/home/pi/py375/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 110, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/tmp/pip-build-env-9n473hi2/overlay/lib/python3.7/site-packages/poetry/masonry/api.py", line 38, in prepare_metadata_for_build_wheel
        poetry = Factory().create_poetry(Path("."))
      File "/tmp/pip-build-env-9n473hi2/overlay/lib/python3.7/site-packages/poetry/factory.py", line 54, in create_poetry
        raise RuntimeError("The Poetry configuration is invalid:\n" + message)
    RuntimeError: The Poetry configuration is invalid:
      - Additional properties are not allowed ('url' was unexpected)
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/pi/py375/bin/python3.7 /home/pi/py375/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpf9arkynj Check the logs for full command output.
"

OS: Ubuntu 18.04
Python version: 3.7.5

**Comment by siddhantgoel** [comment]
This was a bug in 1.5. Could you try installing 1.5.1 or 1.5.2? I just tried it locally and seems to work fine.

**Comment by siddhantgoel** [comment]
I'll mark this issue as closed. If installing 1.5.2 still doesn't work for you, please feel free to re-open.
